### ISSUE TITLE
타일 사이의 경로를 연결할 때 경로를 지우는 도중 커서가 경로를 이탈하면 더 이상 경로가 선택되지 않는 버그

### ISSUE THREAD

**Issue by hyeonki-min** [mididice/Interplaytions#3]
<수정>
타일을 선택 후 이동할 때 생성된 경로 또는 자기 자신으로 이동하면 경로가 겹치면서 더 이상 움직이지 않거나 사용자가 의도한 방향으로 움직이지 않는 버그가 존재

**Comment by hyeonki-min** [comment]
경로를 돌아가서 다른 타일로 이동하면 경로가 더이상 선택되지 않는 로직을 : 새 경로로 선택할 수 있도록 수정

**Comment by hyeonki-min** [comment]
서버가 비정상적으로 작동할때 발생하는 에러
에러 처리 로직 삽입

**Comment by jeeyoonhyun** [comment]
게임 시작 시 서버 상태 체크 후,
서버에 문제있으면 게임시작 안되는걸로 변경하기로함 (후순위기능 추가, 화면 필요)
#13

**Comment by hyeonki-min** [comment]
해당 오류를 로직을 수정하여 
생성된 경로와 자기 자신 타일로는 이동할 수 없도록 변경함
[로직 수정](https://github.com/mididice/Interplaytions/commit/c95c8190653ebf0965c8acc95ff2f40a31af508a)
